name: myteam
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^5.1.0"
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.14
  http: 1.1.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.2.4
  photo_view: ^0.14.0
  flutter_facebook_auth: 6.0.1
  google_sign_in: 6.1.5
  ars_progress_dialog: 0.1.3
  need_resume: ^1.0.7+1
  firebase_core: 2.15.1
  firebase_auth: ^4.9.0
  youtube_player_flutter: ^8.1.2
  video_thumbnail: ^0.5.3
  fluttertoast: ^8.2.2
  image_picker: 1.0.4
  provider: ^6.0.5
  share: ^2.0.4
  dio: 5.3.2
  image_gallery_saver: 2.0.3
  intl: 0.18.1
  firebase_messaging: 14.6.7
  flutter_local_notifications: 15.1.1
  path_provider: ^2.1.1
  permission_handler: 10.4.5
  rxdart: ^0.27.7
  in_app_review: ^2.0.6
  cached_network_image: ^3.2.3
  wakelock: ^0.6.2
  action_broadcast: ^3.0.2
  chewie: ^1.7.1
  video_player: ^2.7.1
  google_mobile_ads: 3.0.0
  facebook_audience_network: ^1.0.1
  flutter_launcher_icons: 0.13.1
  gdpr_dialog: ^2.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dependency_overrides:
  ars_progress_dialog: ">=0.0.2"
  wakelock_plus: ^1.1.1
  win32: ^5.0.7
  flutter_svg: ">=0.22.0 <1.0.0"
  dbus: ^0.7.8
  xml: ^6.4.2
  collection: ^1.18.0


dev_dependencies:
  #  flutter_application_id: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
